version: '2.1'
services:
  ruby:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: rspec
    environment:
      - NEO4J_URL=http://neo4j:password@neo4j:7474
    volumes:
      - .:/app
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/dbms:/data/dbms
